### ISSUE TITLE
chapter-03- express-jwt

### ISSUE THREAD

**Issue by inatu** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#147]
Hello,
It seems that this code broke at "express-jwt": "^7.7.0"

How could I modify this code to work on the the latest version

const requireSignin = expressJwt({
  secret: config.jwtSecret,
  userProperty: 'auth'
})

got the following error:

const requireSignin = express_jwt__WEBPACK_IMPORTED_MODULE_2___default()({
                                                                        ^

TypeError: express_jwt__WEBPACK_IMPORTED_MODULE_2___default(...) is not a function
    at eval (webpack://user_backend/./server/controllers/auth.controller.js?:69:73)
    at Object../server/controllers/auth.controller.js (/Users/natu/qingning_website/user_backend/dist/server.generated.js:29:1)
    at __webpack_require__ (/Users/natu/qingning_website/user_backend/dist/server.generated.js:243:41)
    at eval (webpack://user_backend/./server/routes/user.routes.js?:8:86)
    at Object../server/routes/user.routes.js (/Users/natu/qingning_website/user_backend/dist/server.generated.js:79:1)
    at __webpack_require__ (/Users/natu/qingning_website/user_backend/dist/server.generated.js:243:41)
    at eval (webpack://user_backend/./server/express.js?:20:77)
    at Object../server/express.js (/Users/natu/qingning_website/user_backend/dist/server.generated.js:49:1)
    at __webpack_require__ (/Users/natu/qingning_website/user_backend/dist/server.generated.js:243:41)
    at eval (webpack://user_backend/./server/server.js?:3:66)

**Comment by uladaharanina** [comment]
Hi, I believe we need to do this:

const requireSignin = () => expressJwt({ 
    secret: config.jwtSecret,
    userProperty: 'auth'
  });

And in the user.routes.js apply () to requireSignin.

router.route('/api/users/:userId')
.get(authCtrl.requireSignin(), userCtrl.read)
.put(authCtrl.requireSignin(), authCtrl.hasAuthorization, userCtrl.update)
.delete(authCtrl.requireSignin(), authCtrl.hasAuthorization, userCtrl.remove)

**Comment by shruthis-shetty** [comment]
Hi @inatu , did you got the solution to this issue or still having any issues?
Please reply here the update.

**Comment by JimmyJoggins** [comment]
With "express-jwt": "^8.4.1"

Try adding algorithms as follows:

const requireSignin = expressJwt({
  secret: config.jwtSecret,
  userProperty: 'auth',
  algorithms: ["HS256"]
})

The above approach worked for me. No need to convert authCtrl.requireSignin to a function.

**Comment by shruthis-shetty** [comment]
Hi @inatu , @JimmyJoggins and @wadewilsones , anyone of you please confirm me whether we are good to close this issue?

**Comment by JimmyJoggins** [comment]
Given the level of inactivity, I think probably yes.

**Comment by Apurv-Salunke** [comment]
@inatu I am getting the exact same error. How did you resolve it ?

**Comment by Apurv-Salunke** [comment]
webpack:///./server/controllers/auth.controller.js?:54
const requireSignin = express_jwt__WEBPACK_IMPORTED_MODULE_2___default()({
                                                                        ^

TypeError: express_jwt__WEBPACK_IMPORTED_MODULE_2___default(...) is not a function
    at eval (webpack:///./server/controllers/auth.controller.js?:54:73)
    at ./server/controllers/auth.controller.js (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:29:1)
    at __webpack_require__ (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:233:41)
    at eval (webpack:///./server/routes/user.routes.js?:8:86)
    at ./server/routes/user.routes.js (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:89:1)
    at __webpack_require__ (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:233:41)
    at eval (webpack:///./server/express.js?:18:77)
    at ./server/express.js (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:49:1)
    at __webpack_require__ (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:233:41)
    at eval (webpack:///./server/server.js?:3:66)

Node.js v18.16.0

**Comment by oriankeith002** [comment]
> webpack:///./server/controllers/auth.controller.js?:54 const requireSignin = express_jwt__WEBPACK_IMPORTED_MODULE_2___default()({ ^
> 
> TypeError: express_jwt__WEBPACK_IMPORTED_MODULE_2___default(...) is not a function at eval (webpack:///./server/controllers/auth.controller.js?:54:73) at ./server/controllers/auth.controller.js (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:29:1) at **webpack_require** (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:233:41) at eval (webpack:///./server/routes/user.routes.js?:8:86) at ./server/routes/user.routes.js (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:89:1) at **webpack_require** (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:233:41) at eval (webpack:///./server/express.js?:18:77) at ./server/express.js (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:49:1) at **webpack_require** (/media/apurv/work space/academic projects/mern-stack/social-media/dist/server.generated.js:233:41) at eval (webpack:///./server/server.js?:3:66)
> 
> Node.js v18.16.0

Hi,  import express jwt with a different syntaxt

**Comment by oriankeith002** [comment]
let { expressjwt: expressJwt }  = require('express-jwt');
